



export const Ads = {
    "Nəqliyyat": {
        "Avtomobillər": {
            "BMW": [
                {
                    "id": 1,
                    "title": "BMW 3 Series - Sedan, Sporty Performance",
                    "price": 42000,
                    "description": "A perfect blend of comfort and agility. Experience the sporty performance with advanced features.",
                    "category": "automobile",
                    "image": "https://www.rushlane.com/wp-content/uploads/2022/05/2023-bmw-3-series-facelift-india-launch-price-8-600x338.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 230
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-09-05",
                    "brand": "BMW",
                    "model": "3 Series",
                    "year": 2023,
                    "color": "White",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 5000,
                    "is_new": true
                },
                {
                    "id": 2,
                    "title": "BMW X5 - Luxury SUV with All-Wheel Drive",
                    "price": 65000,
                    "description": "The ultimate luxury SUV offering an all-wheel-drive experience with state-of-the-art technology.",
                    "category": "automobile",
                    "image": "https://img.autobytel.com/chrome/colormatched_01/white/640/cc_2022bms19_01_640/cc_2022bms190019_01_640_475.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 190
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Munich",
                    "date": "2024-09-06",
                    "brand": "BMW",
                    "model": "X5",
                    "year": 2022,
                    "color": "Black",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 15000,
                    "is_new": false
                },
                {
                    "id": 3,
                    "title": "BMW 5 Series - Executive Sedan",
                    "price": 55000,
                    "description": "An executive sedan that combines elegance with advanced driving dynamics.",
                    "category": "automobile",
                    "image": "https://imgd.aeplcdn.com/370x208/n/hcc5i4a_1521693.jpg?q=80",
                    "rating": {
                        "rate": 4.5,
                        "count": 170
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "London",
                    "date": "2024-09-07",
                    "brand": "BMW",
                    "model": "5 Series",
                    "year": 2021,
                    "color": "Blue",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Hybrid",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 20000,
                    "is_new": false
                },
                {
                    "id": 4,
                    "title": "BMW X3 - Compact Luxury SUV",
                    "price": 48000,
                    "description": "Compact yet spacious, the X3 is ideal for city drives and outdoor adventures.",
                    "category": "automobile",
                    "image": "https://images.dealer.com/ddc/vehicles/2022/BMW/X3/SUV/perspective/front-left/2022_76.png",
                    "rating": {
                        "rate": 4.6,
                        "count": 210
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Paris",
                    "date": "2024-09-08",
                    "brand": "BMW",
                    "model": "X3",
                    "year": 2022,
                    "color": "Silver",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "SUV",
                    "mileage": 8000,
                    "is_new": true
                },
                {
                    "id": 5,
                    "title": "BMW M4 - High-Performance Coupe",
                    "price": 72000,
                    "description": "A high-performance coupe designed for speed enthusiasts.",
                    "category": "automobile",
                    "image": "https://cdn.bmwblog.com/wp-content/uploads/2022/10/BMW-M4-xDrive-Competition-Coupe-Imola-Red.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 150
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Dubai",
                    "date": "2024-09-09",
                    "brand": "BMW",
                    "model": "M4",
                    "year": 2023,
                    "color": "Red",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Coupe",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 6,
                    "title": "BMW X7 - Flagship Luxury SUV",
                    "price": 95000,
                    "description": "The largest and most luxurious BMW SUV, offering unmatched comfort and power.",
                    "category": "automobile",
                    "image": "https://platform.cstatic-images.com/in/v2/stock_photos/0d852f0d-b173-412b-ac98-d4550bcb1a96/bfa04392-82ba-48ec-9a66-be64541db163.png",
                    "rating": {
                        "rate": 4.9,
                        "count": 140
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-09-10",
                    "brand": "BMW",
                    "model": "X7",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "3.5L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 5000,
                    "is_new": true
                },
                {
                    "id": 7,
                    "title": "BMW Z4 - Roadster for Pure Driving Pleasure",
                    "price": 58000,
                    "description": "A dynamic roadster that brings open-air driving to life.",
                    "category": "automobile",
                    "image": "https://cloud.leparking.fr/2022/08/19/00/03/bmw-z4-yellow-color-2013-bmw-z4-sdrive28i-for-sale-in-el-reno-ok-73036-vin-is-wball5c58dj104290-yellow_8582154501.jpg",
                    "rating": {
                        "rate": 4.4,
                        "count": 130
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Los Angeles",
                    "date": "2024-09-11",
                    "brand": "BMW",
                    "model": "Z4",
                    "year": 2022,
                    "color": "Yellow",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Roadster",
                    "mileage": 7000,
                    "is_new": false
                },
                {
                    "id": 8,
                    "title": "BMW i8 - Hybrid Sports Car",
                    "price": 140000,
                    "description": "A futuristic sports car combining hybrid technology with stunning design.",
                    "category": "automobile",
                    "image": "https://car-images.bauersecure.com/wp-images/1646/zbmw-097.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 90
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-09-12",
                    "brand": "BMW",
                    "model": "i8",
                    "year": 2021,
                    "color": "Blue",
                    "engine_capacity": "1.5L",
                    "fuel_type": "Hybrid",
                    "transmission": "Automatic",
                    "body_type": "Coupe",
                    "mileage": 15000,
                    "is_new": false
                },
                {
                    "id": 9,
                    "title": "BMW X1 - Compact SAV with BMW DNA",
                    "price": 35000,
                    "description": "Compact size, big potential: The BMW X1 offers great versatility and an authentic BMW experience.",
                    "category": "automobile",
                    "image": "https://di-uploads-pod29.dealerinspire.com/sewellfamilyofcompanies/uploads/2022/12/cosy.arox-2-e1672091097768.png",
                    "rating": {
                        "rate": 4.3,
                        "count": 160
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Toronto",
                    "date": "2024-09-13",
                    "brand": "BMW",
                    "model": "X1",
                    "year": 2023,
                    "color": "White",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 10,
                    "title": "BMW 7 Series - Luxury Sedan",
                    "price": 90000,
                    "description": "A luxurious sedan that redefines driving pleasure with high-end features and performance.",
                    "category": "automobile",
                    "image": "https://www.invygo.com/_next/image?url=https%3A%2F%2Fassets.invygo.com%2Fcar_model_images%2FModel%2520images%2FBMW%2F7%2520series%2F2023%2FTRIMS%2520_%2520SPECS%2F740i%2520sDrive%2FUntitled-5.png&w=640&q=75",
                    "rating": {
                        "rate": 5.0,
                        "count": 100
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Zurich",
                    "date": "2024-09-14",
                    "brand": "BMW",
                    "model": "7 Series",
                    "year": 2023,
                    "color": "Gray",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 1000,
                    "is_new": true
                },
            ],
            "Mercedes": [
                {
                    "id": 11,
                    "title": "Mercedes-Benz C-Class - Compact Executive Sedan",
                    "price": 45000,
                    "description": "A refined and agile compact executive sedan, perfect for urban driving and long journeys.",
                    "category": "automobile",
                    "image": "https://vehicle-images.dealerinspire.com/383d-11001096/W1KAF4HB0PR131456/e86973fd90d486ff4fda16713bb43dae.jpg",
                    "rating": {
                        "rate": 4.6,
                        "count": 210
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-09-15",
                    "brand": "Mercedes-Benz",
                    "model": "C-Class",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 3000,
                    "is_new": true
                },
                {
                    "id": 12,
                    "title": "Mercedes-Benz E-Class - Midsize Luxury Sedan",
                    "price": 60000,
                    "description": "A midsize luxury sedan offering a perfect blend of performance and comfort.",
                    "category": "automobile",
                    "image": "https://65e81151f52e248c552b-fe74cd567ea2f1228f846834bd67571e.ssl.cf1.rackcdn.com/ldm-images/2022-Mercedes-Benz-E-Class-color-Polar-White.png",
                    "rating": {
                        "rate": 4.8,
                        "count": 180
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Munich",
                    "date": "2024-09-16",
                    "brand": "Mercedes-Benz",
                    "model": "E-Class",
                    "year": 2022,
                    "color": "White",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 12000,
                    "is_new": false
                },
                {
                    "id": 13,
                    "title": "Mercedes-Benz GLC - Compact Luxury SUV",
                    "price": 55000,
                    "description": "A stylish compact SUV that combines luxury, versatility, and performance.",
                    "category": "automobile",
                    "image": "https://www.inghamdriven.nz/wp-content/files/stock/CNM/10571/22150_01.jpg?width=2048&optimize=medium",
                    "rating": {
                        "rate": 4.7,
                        "count": 190
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "London",
                    "date": "2024-09-17",
                    "brand": "Mercedes-Benz",
                    "model": "GLC",
                    "year": 2023,
                    "color": "Silver",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 6000,
                    "is_new": true
                },
                {
                    "id": 14,
                    "title": "Mercedes-Benz S-Class - Flagship Luxury Sedan",
                    "price": 120000,
                    "description": "The flagship sedan of Mercedes-Benz, representing the pinnacle of luxury and technology.",
                    "category": "automobile",
                    "image": "https://www.exclusiveautomotivegroup.com/imagetag/3709/9/l/Used-2023-Mercedes-Benz-S-Class-S580-4MATIC-1689617562.jpg",
                    "rating": {
                        "rate": 5.0,
                        "count": 110
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Paris",
                    "date": "2024-09-18",
                    "brand": "Mercedes-Benz",
                    "model": "S-Class",
                    "year": 2023,
                    "color": "Blue",
                    "engine_capacity": "4.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 5000,
                    "is_new": true
                },
                {
                    "id": 15,
                    "title": "Mercedes-Benz GLE - Midsize Luxury SUV",
                    "price": 75000,
                    "description": "A midsize luxury SUV offering superior comfort and performance.",
                    "category": "automobile",
                    "image": "https://cdn-ds.com/blogs-media/sites/178/2022/04/15043940/2022_Mercedes_Benz_AMG_GLE_53_A1_O.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 160
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Dubai",
                    "date": "2024-09-19",
                    "brand": "Mercedes-Benz",
                    "model": "GLE",
                    "year": 2022,
                    "color": "Gray",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 10000,
                    "is_new": false
                },
                {
                    "id": 16,
                    "title": "Mercedes-Benz A-Class - Compact Hatchback",
                    "price": 35000,
                    "description": "A stylish and dynamic compact hatchback perfect for city driving.",
                    "category": "automobile",
                    "image": "https://www.topgear.com/sites/default/files/2023/03/1-Mercedes-A-Class.jpg",
                    "rating": {
                        "rate": 4.5,
                        "count": 140
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-09-20",
                    "brand": "Mercedes-Benz",
                    "model": "A-Class",
                    "year": 2023,
                    "color": "Red",
                    "engine_capacity": "1.5L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Hatchback",
                    "mileage": 2000,
                    "is_new": true
                },
                {
                    "id": 17,
                    "title": "Mercedes-Benz G-Class - Iconic Luxury Off-Roader",
                    "price": 150000,
                    "description": "An iconic luxury off-roader known for its rugged performance and premium features.",
                    "category": "automobile",
                    "image": "https://static.overfuel.com/photos/19/8580/image-2-thumb.webp",
                    "rating": {
                        "rate": 4.9,
                        "count": 100
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Los Angeles",
                    "date": "2024-09-21",
                    "brand": "Mercedes-Benz",
                    "model": "G-Class",
                    "year": 2022,
                    "color": "Black",
                    "engine_capacity": "4.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 8000,
                    "is_new": false
                },
                {
                    "id": 18,
                    "title": "Mercedes-Benz CLA - Compact Luxury Coupe",
                    "price": 45000,
                    "description": "A compact luxury coupe with sporty styling and advanced technology.",
                    "category": "automobile",
                    "image": "https://vehicle-images.dealerinspire.com/1c4c-11001114/W1K5J4GB1PN412898/87039029c161b1811812447ea0b5adce.jpg",
                    "rating": {
                        "rate": 4.4,
                        "count": 130
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-09-22",
                    "brand": "Mercedes-Benz",
                    "model": "CLA",
                    "year": 2023,
                    "color": "White",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Coupe",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 19,
                    "title": "Mercedes-Benz GLA - Compact Luxury Crossover",
                    "price": 40000,
                    "description": "A compact luxury crossover that delivers practicality and style.",
                    "category": "automobile",
                    "image": "https://vehicle-images.dealerinspire.com/27e0-11001114/W1N4N4GB1PJ517953/7c263903549f7c38dcea62f0cdc3dee4.jpg",
                    "rating": {
                        "rate": 4.3,
                        "count": 120
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Toronto",
                    "date": "2024-09-23",
                    "brand": "Mercedes-Benz",
                    "model": "GLA",
                    "year": 2023,
                    "color": "Gray",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 20,
                    "title": "Mercedes-Benz CLS - Stylish Luxury Coupe",
                    "price": 80000,
                    "description": "A stylish luxury coupe offering a blend of comfort, elegance, and dynamic performance.",
                    "category": "automobile",
                    "image": "https://d2ivfcfbdvj3sm.cloudfront.net/7fc965ab77efe6e0fa62e4ca1ea7673bb25f41530c1e3d8e88cb10/stills_0640_png/MY2021/15027/15027_st0640_116.png",
                    "rating": {
                        "rate": 4.9,
                        "count": 90
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Moscow",
                    "date": "2024-09-24",
                    "brand": "Mercedes-Benz",
                    "model": "CLS",
                    "year": 2023,
                    "color": "Silver",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Coupe",
                    "mileage": 500,
                    "is_new": true
                },
            ],
            "Audi": [

                {
                    "id": 21,
                    "title": "Audi A3 - Compact Luxury Sedan",
                    "price": 40000,
                    "description": "A stylish and efficient compact luxury sedan with cutting-edge technology.",
                    "category": "automobile",
                    "image": "https://images.cars.com/cldstatic/wp-content/uploads/audi-a3-2022-01-angle-exterior-front-white.jpg",
                    "rating": {
                        "rate": 4.5,
                        "count": 150
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-09-25",
                    "brand": "Audi",
                    "model": "A3",
                    "year": 2023,
                    "color": "White",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 5000,
                    "is_new": true
                },
                {
                    "id": 22,
                    "title": "Audi A4 - Premium Midsize Sedan",
                    "price": 45000,
                    "description": "A premium midsize sedan offering a blend of comfort, technology, and performance.",
                    "category": "automobile",
                    "image": "https://images.cars.com/cldstatic/wp-content/uploads/audi-a4-2021-01-angle--exterior--front--gray.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 170
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Munich",
                    "date": "2024-09-26",
                    "brand": "Audi",
                    "model": "A4",
                    "year": 2022,
                    "color": "Black",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 10000,
                    "is_new": false
                },
                {
                    "id": 23,
                    "title": "Audi Q5 - Luxury Compact SUV",
                    "price": 55000,
                    "description": "A versatile and luxurious compact SUV designed for both city driving and adventure.",
                    "category": "automobile",
                    "image": "https://media.chromedata.com/MediaGallery/media/MjkzOTU4Xk1lZGlhIEdhbGxlcnk/liuUwSLJ0WRIX7_JclF9X8h-hw2fAQmdJsa0kGSzrdkhZ8iJIBRnbl-ZZZvrSA6Hr4OLW4KlVpfNm5_TQaBDq3kZZotTYfZRjE3wwaqukJRsLYahk-IopoGi7UMGtyPDWEM7hi_En3K5N96-si0Lpg6jCkso_uXIdMFmj4U9-msPwmR0T80OwA/cc_2023AUS020035_01_640_Z7Z7.png",
                    "rating": {
                        "rate": 4.6,
                        "count": 200
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "London",
                    "date": "2024-09-27",
                    "brand": "Audi",
                    "model": "Q5",
                    "year": 2023,
                    "color": "Gray",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 7000,
                    "is_new": true
                },
                {
                    "id": 24,
                    "title": "Audi A6 - Executive Midsize Sedan",
                    "price": 65000,
                    "description": "An executive sedan with advanced technology, luxury features, and dynamic performance.",
                    "category": "automobile",
                    "image": "https://inv.assets.ansira.net/ChromeColorMatch/us/TRANSPARENT_cc_2023AUC020023_01_1280_L5L5.png",
                    "rating": {
                        "rate": 4.8,
                        "count": 140
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Paris",
                    "date": "2024-09-28",
                    "brand": "Audi",
                    "model": "A6",
                    "year": 2023,
                    "color": "Silver",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 8000,
                    "is_new": false
                },
                {
                    "id": 25,
                    "title": "Audi Q7 - Full-Size Luxury SUV",
                    "price": 75000,
                    "description": "A full-size luxury SUV with spacious interior, powerful performance, and cutting-edge technology.",
                    "category": "automobile",
                    "image": "https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/06/2022-Audi-Q7-55-TFSI-quattro-S-line-23.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 110
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Dubai",
                    "date": "2024-09-29",
                    "brand": "Audi",
                    "model": "Q7",
                    "year": 2022,
                    "color": "Blue",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 15000,
                    "is_new": false
                },
                {
                    "id": 26,
                    "title": "Audi Q3 - Compact Crossover SUV",
                    "price": 40000,
                    "description": "A compact crossover SUV with a dynamic design, sporty handling, and premium features.",
                    "category": "automobile",
                    "image": "https://audiapproved.com/_next/image?url=https%3A%2F%2Fadmin.audiapproved.com%2Fuploads%2Fcars%2F95707%2Fupload-1.jpg&w=3840&q=75",
                    "rating": {
                        "rate": 4.4,
                        "count": 90
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-09-30",
                    "brand": "Audi",
                    "model": "Q3",
                    "year": 2023,
                    "color": "Red",
                    "engine_capacity": "2.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 27,
                    "title": "Audi RS7 - High-Performance Sportback",
                    "price": 120000,
                    "description": "A high-performance sportback with aggressive styling and a powerful engine.",
                    "category": "automobile",
                    "image": "https://i.pinimg.com/originals/cb/fb/28/cbfb28b071eccbe5313c6522ebb214b9.jpg",
                    "rating": {
                        "rate": 5.0,
                        "count": 80
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Los Angeles",
                    "date": "2024-10-01",
                    "brand": "Audi",
                    "model": "RS7",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "4.0L",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Sportback",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 28,
                    "title": "Audi A8 - Luxury Full-Size Sedan",
                    "price": 90000,
                    "description": "A luxury full-size sedan with a spacious interior, advanced technology, and powerful engines.",
                    "category": "automobile",
                    "image": "https://hips.hearstapps.com/hmg-prod/images/a218151-medium-1635867809.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 100
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-10-02",
                    "brand": "Audi",
                    "model": "A8",
                    "year": 2022,
                    "color": "Gray",
                    "engine_capacity": "3.0L",
                    "fuel_type": "Diesel",
                    "transmission": "Automatic",
                    "body_type": "Sedan",
                    "mileage": 5000,
                    "is_new": false
                },
                {
                    "id": 29,
                    "title": "Audi e-tron - All-Electric SUV",
                    "price": 70000,
                    "description": "An all-electric SUV offering zero emissions, instant torque, and luxury features.",
                    "category": "automobile",
                    "image": "https://cdn.ebizautos.media/used-2023-audi-e~tron-premiumplusquattro-3620-22355184-1-640.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 140
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Toronto",
                    "date": "2024-10-03",
                    "brand": "Audi",
                    "model": "e-tron",
                    "year": 2023,
                    "color": "Silver",
                    "engine_capacity": "Electric",
                    "fuel_type": "Electric",
                    "transmission": "Automatic",
                    "body_type": "SUV",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 30,
                    "title": "Audi TT - Compact Sports Coupe",
                    "price": 60000,
                    "description": "A compact sports coupe with a sleek design, sporty performance, and modern features.",
                    "category": "automobile",
                    "image": "https://www.motortrend.com/uploads/2022/09/2023-Audi-TT-front-three-quarter-view-5.jpg",
                    "rating": {
                        "rate": 4.6,
                        "count": 110
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Melbourne",
                    "date": "2024-10-04",
                    "brand": "Audi",
                    "model": "TT",
                    "year": 2023,
                    "color": "Yellow",
                    "engine_capacity": "2.5L",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Coupe",
                    "mileage": 0,
                    "is_new": true
                },
            ]
        }
        ,
        "Motosikletlər": {
            "Yamaha": [
                {
                    "id": 31,
                    "title": "Yamaha YZF-R1 - High-Performance Sportbike",
                    "price": 20000,
                    "description": "A high-performance sportbike with cutting-edge technology and dynamic handling.",
                    "category": "motorcycle",
                    "image": "https://cdn.dealerspike.com/imglib/v1/800x600/imglib/Assets/Inventory/C0/FC/C0FCBA54-5BEC-48DD-AC4D-D3963C2F2502.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 300
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-10-05",
                    "brand": "Yamaha",
                    "model": "YZF-R1",
                    "year": 2023,
                    "color": "Blue",
                    "engine_capacity": "998cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sportbike",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 32,
                    "title": "Yamaha MT-07 - Naked Motorcycle",
                    "price": 7500,
                    "description": "A versatile and agile naked motorcycle, perfect for urban commuting and weekend fun.",
                    "category": "motorcycle",
                    "image": "https://cdn.dealerspike.com/imglib/v1/800x600/imglib/Assets/Inventory/23/D6/23D611FE-7990-4C78-82E5-37BD3F9BD512.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 200
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Los Angeles",
                    "date": "2024-10-06",
                    "brand": "Yamaha",
                    "model": "MT-07",
                    "year": 2022,
                    "color": "Gray",
                    "engine_capacity": "689cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Naked",
                    "mileage": 500,
                    "is_new": false
                },
                {
                    "id": 33,
                    "title": "Yamaha NMAX 155 - Compact Scooter",
                    "price": 3000,
                    "description": "A compact scooter ideal for city commuting with a powerful engine and fuel efficiency.",
                    "category": "motorcycle",
                    "image": "https://www.yamaha-motor.co.nz/-/media/products/motorcycle/road/scooter/2022/gpd155an/technical-specifications-panel/2022_gpd155a_wm6_aus_stu_001_800x600.ashx",
                    "rating": {
                        "rate": 4.5,
                        "count": 250
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "London",
                    "date": "2024-10-07",
                    "brand": "Yamaha",
                    "model": "NMAX 155",
                    "year": 2023,
                    "color": "White",
                    "engine_capacity": "155cc",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Scooter",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 34,
                    "title": "Yamaha Tracer 900 GT - Sport Touring Motorcycle",
                    "price": 12500,
                    "description": "A sport touring motorcycle designed for long rides with comfort and agility.",
                    "category": "motorcycle",
                    "image": "https://cdn.dealerspike.com/imglib/v1/800x600/imglib/trimsdb/18165821-9420801-113787991.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 180
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-10-08",
                    "brand": "Yamaha",
                    "model": "Tracer 900 GT",
                    "year": 2022,
                    "color": "Red",
                    "engine_capacity": "847cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Touring",
                    "mileage": 800,
                    "is_new": false
                },
                {
                    "id": 35,
                    "title": "Yamaha Ténéré 700 - Adventure Motorcycle",
                    "price": 10000,
                    "description": "An adventure motorcycle built for off-road exploration and on-road comfort.",
                    "category": "motorcycle",
                    "image": "https://images.medialinksonline.com/imagestream/23187/6045244x1024x0_FFFFFF_L_0.jpg",
                    "rating": {
                        "rate": 4.6,
                        "count": 210
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Sydney",
                    "date": "2024-10-09",
                    "brand": "Yamaha",
                    "model": "Ténéré 700",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "689cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Adventure",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 36,
                    "title": "Yamaha XSR900 - Neo-Retro Motorcycle",
                    "price": 9500,
                    "description": "A neo-retro motorcycle that combines classic design with modern performance.",
                    "category": "motorcycle",
                    "image": "https://images.medialinksonline.com/imagestream/23187/6027666x1024x0_FFFFFF_L_0.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 160
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-10-10",
                    "brand": "Yamaha",
                    "model": "XSR900",
                    "year": 2022,
                    "color": "Silver",
                    "engine_capacity": "847cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Retro",
                    "mileage": 300,
                    "is_new": false
                },
                {
                    "id": 37,
                    "title": "Yamaha FJR1300 - Touring Motorcycle",
                    "price": 15000,
                    "description": "A touring motorcycle with a smooth ride, powerful engine, and advanced technology.",
                    "category": "motorcycle",
                    "image": "https://cdn.powergo.ca/media/catalog/2022/46/572da127f175424fac0bf92f08d8264d_1024x768_webp/2023-yamaha-fjr1300-es-cobalt-blue-7.webp",
                    "rating": {
                        "rate": 4.9,
                        "count": 140
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "San Francisco",
                    "date": "2024-10-11",
                    "brand": "Yamaha",
                    "model": "FJR1300",
                    "year": 2023,
                    "color": "Blue",
                    "engine_capacity": "1298cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Touring",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 38,
                    "title": "Yamaha MT-09 - Hyper Naked Motorcycle",
                    "price": 11000,
                    "description": "A hyper naked motorcycle offering aggressive styling and thrilling performance.",
                    "category": "motorcycle",
                    "image": "https://pbs.twimg.com/media/Fpw2qkbX0AAQNsw.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 190
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Melbourne",
                    "date": "2024-10-12",
                    "brand": "Yamaha",
                    "model": "MT-09",
                    "year": 2023,
                    "color": "Yellow",
                    "engine_capacity": "847cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Naked",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 39,
                    "title": "Yamaha R3 - Entry-Level Sportbike",
                    "price": 5000,
                    "description": "An entry-level sportbike with a lightweight frame and agile performance, perfect for beginners.",
                    "category": "motorcycle",
                    "image": "https://cdn2.yamaha-motor.eu/prod/product-assets/2022/YZF-R320/2022-Yamaha-YZF-R320-EU-Yamaha_Black-Studio-001-03.jpg",
                    "rating": {
                        "rate": 4.5,
                        "count": 300
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Chicago",
                    "date": "2024-10-13",
                    "brand": "Yamaha",
                    "model": "R3",
                    "year": 2022,
                    "color": "Black",
                    "engine_capacity": "321cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sportbike",
                    "mileage": 150,
                    "is_new": false
                },
                {
                    "id": 40,
                    "title": "Yamaha YZF-R6 - Track-Ready Supersport",
                    "price": 12000,
                    "description": "A track-ready supersport motorcycle with an aggressive design and powerful engine.",
                    "category": "motorcycle",
                    "image": "https://static1.hotcarsimages.com/wordpress/wp-content/uploads/2020/07/Yamaha-YZF-R6-Motorbike.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 230
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Paris",
                    "date": "2024-10-14",
                    "brand": "Yamaha",
                    "model": "YZF-R6",
                    "year": 2023,
                    "color": "Blue",
                    "engine_capacity": "599cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sportbike",
                    "mileage": 0,
                    "is_new": true
                }
            ],
            "Honda": [
                {
                    "id": 41,
                    "title": "Honda CBR1000RR - Superbike",
                    "price": 18000,
                    "description": "A high-performance superbike with advanced aerodynamics and cutting-edge technology.",
                    "category": "motorcycle",
                    "image": "https://wieck-honda-production.s3.amazonaws.com/photos/0f2111ffe6c64e0f86bc2858fef2243348c6375c/preview-928x522.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 320
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-10-15",
                    "brand": "Honda",
                    "model": "CBR1000RR",
                    "year": 2023,
                    "color": "Red",
                    "engine_capacity": "999cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sportbike",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 42,
                    "title": "Honda CRF1100L Africa Twin - Adventure Motorcycle",
                    "price": 14000,
                    "description": "An adventure motorcycle designed for both off-road exploration and on-road comfort.",
                    "category": "motorcycle",
                    "image": "https://media.zigcdn.com/media/model/2023/May/africa-twin-right-side-view_360x240.jpg",
                    "rating": {
                        "rate": 4.9,
                        "count": 210
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Cape Town",
                    "date": "2024-10-16",
                    "brand": "Honda",
                    "model": "CRF1100L Africa Twin",
                    "year": 2022,
                    "color": "White",
                    "engine_capacity": "1084cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Adventure",
                    "mileage": 500,
                    "is_new": false
                },
                {
                    "id": 43,
                    "title": "Honda Rebel 500 - Cruiser Motorcycle",
                    "price": 6200,
                    "description": "A lightweight cruiser motorcycle with a minimalist design, perfect for new riders.",
                    "category": "motorcycle",
                    "image": "https://www.hondaireland.ie/assets/2022/11/Screenshot-2022-11-07-at-14.08.04-640x425.png",
                    "rating": {
                        "rate": 4.7,
                        "count": 160
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Los Angeles",
                    "date": "2024-10-17",
                    "brand": "Honda",
                    "model": "Rebel 500",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "471cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Cruiser",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 44,
                    "title": "Honda CB650R - Neo Sports Café Motorcycle",
                    "price": 9500,
                    "description": "A neo sports café motorcycle that blends modern performance with retro style.",
                    "category": "motorcycle",
                    "image": "https://storage.googleapis.com/superbike_news/2021/11/2022-Honda-CB650R-02-696x521.jpg",
                    "rating": {
                        "rate": 4.8,
                        "count": 190
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-10-18",
                    "brand": "Honda",
                    "model": "CB650R",
                    "year": 2022,
                    "color": "Gray",
                    "engine_capacity": "649cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sport",
                    "mileage": 300,
                    "is_new": false
                },
                {
                    "id": 45,
                    "title": "Honda Gold Wing - Touring Motorcycle",
                    "price": 25000,
                    "description": "A luxury touring motorcycle with a smooth ride and advanced comfort features.",
                    "category": "motorcycle",
                    "image": "https://www.bike-parts-honda.com/thumbs/h/ident_photos/300_300/GL1800DAN-B197H.jpg",
                    "rating": {
                        "rate": 5.0,
                        "count": 120
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Paris",
                    "date": "2024-10-19",
                    "brand": "Honda",
                    "model": "Gold Wing",
                    "year": 2023,
                    "color": "Blue",
                    "engine_capacity": "1833cc",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Touring",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 46,
                    "title": "Honda PCX 150 - Scooter",
                    "price": 3500,
                    "description": "A compact scooter designed for urban commuting with excellent fuel efficiency.",
                    "category": "motorcycle",
                    "image": "https://cdn-fastly.motorcycle.com/media/2023/02/26/8966422/2021-honda-pcx-lineup-announced-for-japan-including-new-pcx-160.jpg?size=720x845&nocrop=1",
                    "rating": {
                        "rate": 4.6,
                        "count": 220
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "London",
                    "date": "2024-10-20",
                    "brand": "Honda",
                    "model": "PCX 150",
                    "year": 2022,
                    "color": "Red",
                    "engine_capacity": "150cc",
                    "fuel_type": "Petrol",
                    "transmission": "Automatic",
                    "body_type": "Scooter",
                    "mileage": 200,
                    "is_new": false
                },
                {
                    "id": 47,
                    "title": "Honda CB500X - Adventure Motorcycle",
                    "price": 7500,
                    "description": "An adventure motorcycle perfect for both city commuting and weekend adventures.",
                    "category": "motorcycle",
                    "image": "https://roaddirt.tv/wp-content/uploads/2023/08/IMG_4075-1024x640.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 180
                    },
                    "VIP": true,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Sydney",
                    "date": "2024-10-21",
                    "brand": "Honda",
                    "model": "CB500X",
                    "year": 2023,
                    "color": "Black",
                    "engine_capacity": "471cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Adventure",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 48,
                    "title": "Honda CRF450R - Motocross Motorcycle",
                    "price": 9800,
                    "description": "A motocross motorcycle with a lightweight frame and powerful engine for competitive racing.",
                    "category": "motorcycle",
                    "image": "https://cdn.room58.com/2023/02/27/e24247e0ae90dd30a46ca94d79bd2959_7852844bfd19bbdd.webp",
                    "rating": {
                        "rate": 4.9,
                        "count": 140
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-10-22",
                    "brand": "Honda",
                    "model": "CRF450R",
                    "year": 2023,
                    "color": "Red",
                    "engine_capacity": "450cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Motocross",
                    "mileage": 0,
                    "is_new": true
                },
                {
                    "id": 49,
                    "title": "Honda NC750X - Adventure Touring Motorcycle",
                    "price": 10500,
                    "description": "An adventure touring motorcycle with a comfortable ride and ample storage space.",
                    "category": "motorcycle",
                    "image": "https://images5.1000ps.net/images_bikekat/2022/2-Honda/9204-NC750X_DCT/005-637774831308800994-honda-nc750x-dct.jpg?format=webp&quality=80&scale=both&width=1984&height=1116&bgcolor=rgba_39_42_44_0&mode=pad",
                    "rating": {
                        "rate": 4.8,
                        "count": 200
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Berlin",
                    "date": "2024-10-23",
                    "brand": "Honda",
                    "model": "NC750X",
                    "year": 2022,
                    "color": "White",
                    "engine_capacity": "745cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Touring",
                    "mileage": 600,
                    "is_new": false
                },
                {
                    "id": 50,
                    "title": "Honda CB300R - Neo Sports Café Motorcycle",
                    "price": 4800,
                    "description": "A neo sports café motorcycle ideal for beginners, combining a lightweight design with agile performance.",
                    "category": "motorcycle",
                    "image": "https://www.canaryride.com/wp-content/uploads/2023/06/362317_2022_HONDA_CB300R.jpg.webp",
                    "rating": {
                        "rate": 4.6,
                        "count": 180
                    },
                    "VIP": false,
                    "Premium": false,
                    "view_count": 0,
                    "store": true,
                    "location": "Madrid",
                    "date": "2024-10-24",
                    "brand": "Honda",
                    "model": "CB300R",
                    "year": 2023,
                    "color": "Silver",
                    "engine_capacity": "286cc",
                    "fuel_type": "Petrol",
                    "transmission": "Manual",
                    "body_type": "Sport",
                    "mileage": 0,
                    "is_new": true
                }
            ]
        }
    },
    "Elektronika": {
        "Telefonlar": {
            "Apple": [
                {
                    "id": 51,
                    "title": "iPhone 15 Pro Max",
                    "price": 1199,
                    "description": "The iPhone 15 Pro Max offers a stunning display, powerful performance, and advanced camera features.",
                    "category": "smartphone",
                    "image": "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-7inch-whitetitanium?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=VW44dkRidm5wazhwcGxtL0cyaEJ2VTkrNXBUdUJSK1k4NE5seUtJaW80ZkRmbnd3M3NkTWdNTTIrREE3akpCaWlCQmV2WTA2cncybDF2YzFnKzI0S3J4M3lYcDIyK01lckZBaW5GTC9DMEQxcjBVRyswWG14bEI4WVZBcUIybEZjbk10T2pDQ3hjTkVEUGVzeFhCeVRnPT0=&traceId=1",
                    "rating": {
                        "rate": 4.9,
                        "count": 500
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "San Francisco",
                    "date": "2024-10-01",
                    "brand": "Apple",
                    "model": "iPhone 15 Pro Max",
                    "year": 2024,
                    "color": "Titanium",
                    "storage_capacity": "1TB",
                    "battery_life": "29 hours",
                    "screen_size": "6.7 inches",
                    "processor": "A17 Bionic",
                    "camera": "48MP Triple Camera",
                    "is_new": true
                },
                {
                    "id": 52,
                    "title": "iPhone 15",
                    "price": 999,
                    "description": "The iPhone 15 brings exceptional performance, a gorgeous display, and new camera features in a compact design.",
                    "category": "smartphone",
                    "image": "https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-15-finish-select-202309-6-1inch-blue?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=cHJOTXEwTU92OEtKVDV2cVB1R2FTSjlERndlRTljaUdZeHJGM3dlLzR2OGlYQ0tYMHd1OS9ZREtnNzFSR1owOHF2TWlpSzUzejRCZGt2SjJUNGl1VExZc3g4ZkhUVEc0bFNFL1l3MHJZd1VOWURGTDRNb1FOSGhVN2M4eGh6OGY=&traceId=1",
                    "rating": {
                        "rate": 4.8,
                        "count": 450
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "New York",
                    "date": "2024-10-02",
                    "brand": "Apple",
                    "model": "iPhone 15",
                    "year": 2024,
                    "color": "Blue",
                    "storage_capacity": "512GB",
                    "battery_life": "27 hours",
                    "screen_size": "6.1 inches",
                    "processor": "A16 Bionic",
                    "camera": "48MP Dual Camera",
                    "is_new": true
                }
            ],
            "Samsung": [
                {
                    "id": 61,
                    "title": "Samsung Galaxy S24 Ultra",
                    "price": 1299,
                    "description": "The Samsung Galaxy S24 Ultra offers a premium experience with a high-resolution display, powerful processor, and an advanced camera system.",
                    "category": "smartphone",
                    "image": "https://images.samsung.com/az/smartphones/galaxy-s24-ultra/images/galaxy-s24-ultra-highlights-color-titanium-black-back-mo.jpg?imbypass=true",
                    "rating": {
                        "rate": 4.7,
                        "count": 600
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Seoul",
                    "date": "2024-11-01",
                    "brand": "Samsung",
                    "model": "Galaxy S24 Ultra",
                    "year": 2024,
                    "color": "Phantom Black",
                    "storage_capacity": "1TB",
                    "battery_life": "30 hours",
                    "screen_size": "6.8 inches",
                    "processor": "Exynos 2400",
                    "camera": "200MP Quad Camera",
                    "is_new": true
                },
                {
                    "id": 62,
                    "title": "Samsung Galaxy Note 20",
                    "price": 999,
                    "description": "The Samsung Galaxy Note 20 is designed for productivity and performance with its large display, S Pen, and powerful hardware.",
                    "category": "smartphone",
                    "image": "https://images.samsung.com/latin_en/smartphones/galaxy-note20/models/images/galaxy-note20-ultra_models_colors_mystic-bronze-front_s.jpg",
                    "rating": {
                        "rate": 4.5,
                        "count": 400
                    },
                    "VIP": false,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Tokyo",
                    "date": "2024-11-02",
                    "brand": "Samsung",
                    "model": "Galaxy Note 20",
                    "year": 2024,
                    "color": "Mystic Bronze",
                    "storage_capacity": "512GB",
                    "battery_life": "25 hours",
                    "screen_size": "6.7 inches",
                    "processor": "Snapdragon 888",
                    "camera": "64MP Triple Camera",
                    "is_new": true
                }
            ]
        },
        "Kompüterlər": {
            "Dell": [
                {
                    "id": 71,
                    "title": "Dell XPS 15",
                    "price": 1899,
                    "description": "The Dell XPS 15 combines power and portability with its 15.6-inch InfinityEdge display, high-performance components, and sleek design.",
                    "category": "laptop",
                    "image": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/xps-notebooks/xps-15-9530/media-gallery/touch-black/notebook-xps-15-9530-t-black-gallery-4.psd?fmt=pjpg&pscan=auto&scl=1&wid=3482&hei=2067&qlt=100,1&resMode=sharp2&size=3482,2067&chrss=full&imwidth=5000",
                    "rating": {
                        "rate": 4.6,
                        "count": 250
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Round Rock",
                    "date": "2024-10-15",
                    "brand": "Dell",
                    "model": "XPS 15",
                    "year": 2024,
                    "color": "Platinum Silver",
                    "processor": "Intel Core i7-13700H",
                    "ram": "16GB",
                    "storage": "512GB SSD",
                    "screen_size": "15.6 inches",
                    "battery_life": "18 hours",
                    "is_new": true
                },
                {
                    "id": 72,
                    "title": "Dell Alienware x17",
                    "price": 2299,
                    "description": "The Dell Alienware x17 is designed for gaming enthusiasts, offering high-end performance, a large 17.3-inch display, and customizable RGB lighting.",
                    "category": "gaming laptop",
                    "image": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/dell-client-products/notebooks/alienware-notebooks/alienware-x17-r2/media-gallery/updated/laptop-alienware-x17-r2-gray-gallery-7.psd?fmt=pjpg&pscan=auto&scl=1&wid=4171&hei=2700&qlt=100,1&resMode=sharp2&size=4171,2700&chrss=full&imwidth=5000",
                    "rating": {
                        "rate": 4.8,
                        "count": 150
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Austin",
                    "date": "2024-10-20",
                    "brand": "Dell",
                    "model": "Alienware x17",
                    "year": 2024,
                    "color": "Lunar Light",
                    "processor": "Intel Core i9-13900K",
                    "ram": "32GB",
                    "storage": "1TB SSD",
                    "screen_size": "17.3 inches",
                    "battery_life": "12 hours",
                    "is_new": true
                }
            ],
            "MacBook": [
                {
                    "id": 81,
                    "title": "MacBook Air M2",
                    "price": 1199,
                    "description": "The MacBook Air M2 is Apple's latest ultra-thin laptop featuring the M2 chip, a stunning Retina display, and all-day battery life.",
                    "category": "laptop",
                    "image": "https://laptopmedia.com/wp-content/uploads/2022/08/7-8.jpg",
                    "rating": {
                        "rate": 4.7,
                        "count": 300
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Cupertino",
                    "date": "2024-11-01",
                    "brand": "Apple",
                    "model": "MacBook Air M2",
                    "year": 2024,
                    "color": "Space Gray",
                    "processor": "Apple M2",
                    "ram": "8GB",
                    "storage": "256GB SSD",
                    "screen_size": "13.6 inches",
                    "battery_life": "18 hours",
                    "is_new": true
                },
                {
                    "id": 82,
                    "title": "MacBook Pro 16-inch",
                    "price": 2499,
                    "description": "The MacBook Pro 16-inch is designed for professionals, featuring Apple's M1 Pro or M1 Max chip, a large high-resolution display, and enhanced performance for demanding tasks.",
                    "category": "laptop",
                    "image": "https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/refurb-mbp16touch-silver-gallery-2019_GEO_AU?wid=1250&hei=1200&fmt=jpeg&qlt=95&.v=1626200862000",
                    "rating": {
                        "rate": 4.9,
                        "count": 200
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Cupertino",
                    "date": "2024-11-15",
                    "brand": "Apple",
                    "model": "MacBook Pro 16-inch",
                    "year": 2024,
                    "color": "Silver",
                    "processor": "Apple M1 Max",
                    "ram": "32GB",
                    "storage": "1TB SSD",
                    "screen_size": "16 inches",
                    "battery_life": "21 hours",
                    "is_new": true
                }
            ]
        }
    },
    "Xidmətlər": {
        "Təmir": {
            "Avtomobil təmiri": [
                {
                    "id": 9999299,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ],
            "Ev təmiri": [
                {
                    "id": 9999599,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ]
        },
        "Təhsil": {
            "Dərslər": [
                {
                    "id": 9999899,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ],
            "Təlimlər": [
                {
                    "id": 9899999,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ]
        }
    },
    "Biznes": {
        "Ofis Əşyaları": {
            "Masa": [
                {
                    "id": 999999,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ],
            "Stul": [
                {
                    "id": 999999,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ]
        },
        "Reklam və Marketinq": {
            "Reklam kampaniyaları": [
                {
                    "id": 999999,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ],
            "Marketinq strategiyaları": [
                {
                    "id": 999999,
                    "title": "test",
                    "price": 9999,
                    "description": "test",
                    "category": "test",
                    "image": "https://global-sensors.com/wp-content/uploads/2021/07/test.jpg",
                    "rating": {
                        "rate": 999,
                        "count": 99
                    },
                    "VIP": true,
                    "Premium": true,
                    "view_count": 0,
                    "store": true,
                    "location": "Test",
                    "date": "0000-00-00",
                    "brand": "test",
                    "model": "test",
                    "year": 2024,
                    "color": "test",
                    "storage_capacity": "test",
                    "battery_life": "test",
                    "screen_size": "test",
                    "processor": "test",
                    "camera": "test",
                    "is_new": true
                },
            ]
        }
    },
    "Şəxsi əşyalar": {
        "Geyim": {
            "Köynək": [],
            "Şalvar": []
        },
        "Aksesuarlar": {
            "Saat": [],
            "Eynək": []
        }
    },
    "Hobbi və Asudə": {
        "İdman": {
            "Futbol Topu": [],
            "Boks Əlcəyi": []
        },
        "Əl İşləri": {
            "Rəsm": [],
            "Toxumalar": []
        }
    },
    "Uşaq aləmi": {
        "Oyuncaq": {
            "Maşın": [],
            "Lego": []
        },
        "Geyim": {
            "Uşaq Geyimi": [],
            "Ayakkabılar": []
        }
    },
    "Heyvanlar": {
        "Ev Heyvanları": {
            "İt": [],
            "Pişik": []
        },
        "Təsərüfat Heyvanları": {
            "At": [],
            "İnək": []
        }
    },
    "İş elanları": {
        "Tam Zamanlı": {
            "Mühəndis": [],
            "Satış Meneceri": []
        },
        "Qismən Zamanlı": {
            "Ofis Köməkçisi": [],
            "Kuryer": []
        }
    },
    "Velosipedlər": {
        "Yol Velosipedləri": {
            "Bianci": [],
            "Steels": []
        },
        "Dağ Velosipedləri": {
            "Trek marlin 5": [],
            "Trinix M136": []
        }
    }
}